[window]
# This section is optional but recommended for a complete look.
decorations = "full"

[colors]
# Magikarp Splash by Jules

# Primary colors
primary.background = "#a1422a"
primary.foreground = "#ffd998"

# Cursor colors
cursor.cursor = "#ffd998"
cursor.text = "#a1422a"

# Selection colors
selection.background = "#e3b15a"
selection.text = "#a1422a"

# Normal colors
normal.black = "#3d3d3d"
normal.red = "#df7669"
normal.green = "#e3b15a"
normal.yellow = "#e3b15a"
normal.blue = "#c76449"
normal.magenta = "#e7b9bb"
normal.cyan = "#c76449"
normal.white = "#ffd998"

# Bright colors
bright.black = "#585858"
bright.red = "#df7669"
bright.green = "#e3b15a"
bright.yellow = "#e3b15a"
bright.blue = "#c76449"
bright.magenta = "#e7b9bb"
bright.cyan = "#c76449"
bright.white = "#ffd998"
